language: python
install:
  - pip install tox
  - pip install pyflakes
  - pip install coveralls
services:
  - redis-server
notifications:
  email:
    recipients:
    - justin@justinholmes.com
    on_success: change
    on_failure: always
script: tox

after_success:
  - coveralls